customhost = "employee001.clieghp4odrm.ap-south-1.rds.amazonaws.com"
customuser = "Intellipaat"
custompass = "intellipaat123"
customdb = "employee001"
custombucket = "addemployee"
customregion = "ap-south-1"
